apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-sentinel-3
  namespace: redis-sentinel
  labels:
    app: redis-sentinel
    node-id: redis-sentinel-3

spec:
  replicas: 1
  selector:
    app: redis-sentinel
    node-id: redis-sentinel-3

  template:
    metadata:
      labels:
        app: redis-sentinel
        node-id: redis-sentinel-3
    spec:
      containers:
      - name: redis-sentinel
        image: mpschmidt/elastic-redis:3.2.5-1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: "REDIS_NODE_TYPE"
          value: "SENTINEL"
        - name: "SENTINEL_MASTER_ID"
          value: "mymaster"
        - name: "SENTINEL_SERVICE_HOST"
          value: "${REDIS_SENTINEL_SERVICE_HOST}"
        - name: "SENTINEL_SERVICE_PORT"
          value: "${REDIS_SENTINEL_SERVICE_PORT}"
        - name: "SENTINEL_INIT_MASTER_HOST"
          value: "${REDIS_NODE_1_SERVICE_HOST}"
        - name: "SENTINEL_INIT_MASTER_PORT"
          value: "${REDIS_NODE_1_SERVICE_PORT}"
        - name: "SENTINEL_CONFIG"
          value: |
            sentinel myid aaaabbbbccccddddeeee00000000000000000003
            sentinel monitor ${SENTINEL_MASTER_ID} ${MASTER_IP} ${MASTER_PORT} 2
            sentinel down-after-milliseconds ${SENTINEL_MASTER_ID} 20000
            sentinel failover-timeout ${SENTINEL_MASTER_ID} 60000
            sentinel parallel-syncs ${SENTINEL_MASTER_ID} 1
            bind 0.0.0.0
        ports:
        - name: redis-sentinel
          containerPort: 26379
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 26379
          initialDelaySeconds: 30
          timeoutSeconds: 5